site_name: SurveyCompo Docs
site_url: https://doc.surveycompo.com
theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    - navigation.footer
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  logo: assets/logo.png
  favicon: assets/icons/favicon-32x32.png
  font:
    text: Inter
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: white
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: grey
      accent: blue

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://tag.surveycompo.com/v1.js
  - javascripts/doc.js

extra:
  homepage: https://www.surveycompo.com
  generator: false # hide Make by Mkdocs
  analytics:
    provider: google
    property: G-M9G5HS23NK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  # - mkdocs-nav-weight # We don't need this since we have 'nav' instead.
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

nav:
  - "index.md"
  - "Tutorial":
      - "tutorial/building.md"
      - "tutorial/publishing.md"
  - "Data Models":
      - "data-models/survey.md"
      - "data-models/screen.md"
      - "data-models/page.md"
      - "data-models/block.md"
      - "data-models/input.md"
      - "data-models/other-models.md"
  - "Input Types":
      - "input-types/overview.md"
      - "input-types/checkbox.md"
      - "input-types/checkbox-text.md"
      - "input-types/radio.md"
      - "input-types/radio-text.md"
      - "input-types/text.md"
      - "input-types/textarea.md"
      - "input-types/dropdown.md"
      - "input-types/number-scale.md"
      - "input-types/star-scale.md"
      - "input-types/image.md"
      - "input-types/toggle.md"
      - "input-types/likert.md"
      - "input-types/likert-matrix.md"
  - "Customization":
      - "customization/overview.md"
      - "customization/toplevel.md"
      - "customization/theme.md"
      - "customization/css.md"
      - "customization/custom-html.md"
      - "customization/layout.md"
  - "Advanced Features":
      - "advanced/randomization.md"
      - "advanced/variables.md"
      - "advanced/piping.md"
      - "advanced/conditional-logic.md"
      - "advanced/disqualification.md"
      - "advanced/validation.md"
      - "advanced/templates.md"
      - "advanced/prefill.md"
  - "publish.md"
  - "Integration":
      - "integration/component.md"
      - "integration/event-and-api.md"
      - "integration/data-collection.md"
      - "integration/webhooks.md"
      - "integration/react.md"
      - "integration/angular.md"
      - "integration/vue.md"
  - "Miscellaneous":
      - "miscellaneous/browser-supports.md"
      - "miscellaneous/feedback-and-issues.md"

copyright: |
  &copy; 2024 <a href="https://www.surveycompo.com"  target="_blank" rel="noopener">SurveyCompo</a>
  &nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.surveycompo.com/privacy"  target="_blank" rel="noopener">Privacy</a>
  &nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.surveycompo.com/terms"  target="_blank" rel="noopener">Terms of Service</a>
