site_name: SurveyCompo
site_url: https://www.surveycompo.com
theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  logo: assets/logo.png
  favicon: assets/icons/favicon-32x32.png
  font:
    text: Inter
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: white
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: grey
      accent: blue

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://tag.surveycompo.com/v1.js
  - javascripts/doc.js

extra:
  homepage: https://www.surveycompo.com
  generator: false # hide Make by Mkdocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - mkdocs-nav-weight
  - search

copyright: |
  &copy; 2024 <a href="https://www.surveycompo.com"  target="_blank" rel="noopener">SurveyCompo</a>
  &nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.surveycompo.com/privacy"  target="_blank" rel="noopener">Privacy</a>
  &nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.surveycompo.com/terms"  target="_blank" rel="noopener">Terms of Service</a>
